FROM golang:1.24-alpine AS builder
WORKDIR /src
RUN apk add git make
RUN git clone https://github.com/doganarif/portfinder.git .
ENV GOFLAGS="-mod=mod"
RUN go mod download
RUN go build -v -o /bin/pf ./cmd/portfinder

FROM alpine:latest
COPY --from=builder /bin/pf /usr/local/bin/pf
ENTRYPOINT ["pf"]
