---
# tasks file for deploy_cjson
- name: Sanity check (Sprawdzenie wolnego miejsca)
  command: df -h /
  register: df_output
  failed_when: false

- name: Instalacja silnika Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Wysłanie pliku aplikacji (.tar.gz)
  copy:
    src: my-app.tar.gz
    dest: /opt/my-app.tar.gz

- name: Oczyszczenie środowiska
  file:
    path: /opt/my-app.tar.gz
    state: absent
