#pobranie i wejście do obrazu z sdk
FROM mcr.microsoft.com/dotnet/sdk:10.0

#aktualizacja i instalacje gita z kompatybilnością wsteczną
RUN apt-get update && apt-get install -y git mono-complete

#ustawienie katalogu roboczego
WORKDIR /app

#pobieramy repo
RUN git clone https://github.com/Humanizr/Humanizer.git .

#budujemy
RUN dotnet build
