FROM ubuntu:24.04

RUN apt-get update && apt-get install -y git build-essential cmake && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/DaveGamble/cJSON.git .

RUN make

CMD ["/bin/bash"]