apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf419850-web
  labels:
    app: mf419850-web
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mf419850-web
  template:
    metadata:
      labels:
        app: mf419850-web
    spec:
      containers:
        - name: mf419850-web
          image: 10.0.2.3:5000/mf419850-web:latest
          ports:
            - containerPort: 80
