apiVersion: apps/v1
kind: Deployment
metadata:
  name: yahtzee-deployment
  labels:
    app: yahtzee
spec:
  replicas: 4
  selector:
    matchLabels:
      app: yahtzee
  template:
    metadata:
      labels:
        app: yahtzee
    spec:
      containers:
      - name: game-container
        image: moja-gra:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80