---
- name: Usuniecie kontenera nginx z Endpoints
  hosts: Endpoints
  become: true
  tasks:
    - name: Usun kontener lab8-nginx
      ansible.builtin.command: docker rm -f lab8-nginx
      ignore_errors: true
      changed_when: true

    - name: Sprawdz czy kontener zostal usuniety
      ansible.builtin.command: docker ps -a --filter name=lab8-nginx
      register: docker_ps_after
      changed_when: false

    - name: Pokaz wynik po usunieciu
      ansible.builtin.debug:
        var: docker_ps_after.stdout_lines
