---
- name: Instalacja Dockera na Endpoints
  hosts: Endpoints
  become: true
  tasks:
    - name: Instalacja dockera
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Uruchom docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Dodaj ansible do grupy docker
      ansible.builtin.user:
        name: ansible
        groups: docker
        append: true

    - name: Sprawdz wersje dockera
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Pokaz wersje dockera
      ansible.builtin.debug:
        var: docker_version.stdout
