FROM gcc:latest

WORKDIR /app

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/deftio/C-and-Cpp-Tests-with-CI-CD-Example.git

WORKDIR /app/C-and-Cpp-Tests-with-CI-CD-Example

RUN make