apiVersion: v1
kind: Service
metadata:
  name: canary-service
spec:
  ports:
  - port: 80
  selector:
    app: canary-app 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
        version: v1
    spec:
      containers:
      - name: nginx
        image: piti83/lab11-nginx:v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app
  template:
    metadata:
      labels:
        app: canary-app
        version: v2
    spec:
      containers:
      - name: nginx
        image: piti83/lab11-nginx:v2