pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                git branch: 'DP423171',
                    url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2026_ITE.git'
            }
        }
        stage('build') {
            stages {
                stage('build:main') {
                    steps {
                        script {
                            docker.build("build-env-main:latest", "ITe/5/DP423171/Sprawozdanie3/docker/main")
                        }
                    }
                }
                stage('build:test') {
                    steps {
                        script {
                            image = docker.build("build-env-test:latest", "ITe/5/DP423171/Sprawozdanie3/docker/test")
                            image.withRun { c ->
                                sh """
                                    mkdir -p meson-logs
                                    docker cp ${c.id}:/repo/build/meson-logs/testlog.junit.xml meson-logs/testlog.junit.xml
                                """
                            }
                        }
                    }
                    post {
                        always {
                            script {
                                junit 'meson-logs/testlog.junit.xml'
                            }
                        }
                    }
                }
            }
        }
    }
}
