pipeline {
    agent none
    
    stages {
        stage('Checkout') {
            agent any
            steps {
                echo 'Klonowanie repozytorium...'
                checkout scm
                echo "Budowanie commita: ${env.GIT_COMMIT}"
            }
        }

        stage('Build and Test') {
            agent any  // Dodajemy agenta
            steps {
                // Zmień katalog na projektowy
                dir('grupa2/MF419850/test_project') {
                    script {
                        // Zbuduj obraz używając Dockerfile w bieżącym katalogu
                        def buildImage = docker.build('hello-build', '.')
                        
                        // Uruchom build i testy wewnątrz kontenera
                        buildImage.inside {
                            sh 'make clean'
                            sh 'make'
                            sh 'make test'
                        }
                    }
                }
            }
            post {
                success {
                    echo 'Build i testy zakończone sukcesem!'
                }
                failure {
                    echo 'Build lub testy zakończone niepowodzeniem.'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline zakończony.'
        }
    }
}
