---
- name: Zdalne wywoływanie procedur
  hosts: all
  become: true

  tasks:

    - name: Ping wszystkich hostów
      ansible.builtin.ping:

    - name: Skopiuj inventory na maszyny
      ansible.builtin.copy:
        src: inventory.ini
        dest: /tmp/inventory.ini

    - name: Ponownie skopiuj inventory na maszyny
      ansible.builtin.copy:
        src: inventory.ini
        dest: /tmp/inventory.ini

    - name: Aktualizacja pakietów
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Restart rng-tools
      ansible.builtin.service:
        name: rng-tools
        state: restarted
