---
- name: Kopiuj plik inwentaryzacji na Endpoints
  hosts: Endpoints
  tasks:
    - name: Kopiuj inventory.ini
      ansible.builtin.copy:
        src: ../inventory.ini
        dest: /home/ansible/inventory.ini
        owner: ansible
        mode: '0644'
