---
- name: restart uslug sshd i rngd
  hosts: Endpoints
  become: true
  tasks:
    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: restart rngd
      ansible.builtin.service:
        name: rngd
        state: restarted
      ignore_errors: true
