pipeline {
    agent any
    environment {
        APP_VERSION = "1.0.${env.BUILD_ID}"
        IMAGE_NAME = "express-api"
        WORK_DIR = "grupa4/TM424276/Sprawozdanie7/aplikacja_node"
    }
    stages {
        stage('Budowanie i Testowanie') {
            steps {
                dir("${WORK_DIR}") {
                    // DODANO --no-cache
                    sh 'docker build --no-cache --target test -t ${IMAGE_NAME}-test .'
                }
            }
        }
        stage('Budowanie Obrazu Deploy') {
            steps {
                dir("${WORK_DIR}") {
                    // DODANO --no-cache
                    sh 'docker build --no-cache --target deploy -t ${IMAGE_NAME}:${APP_VERSION} .'
                }
            }
        }
        stage('Smoke Test (Weryfikacja)') {
            steps {
                dir("${WORK_DIR}") {
                    sh 'docker run -d --name smoke-test-app ${IMAGE_NAME}:${APP_VERSION}'
                    sleep 5
                    sh 'docker exec smoke-test-app wget -qO- http://localhost:3000/ || exit 1'
                }
            }
            post {
                always { sh 'docker rm -f smoke-test-app' }
            }
        }
        stage('Publikacja Artefaktu') {
            steps {
                dir("${WORK_DIR}") {
                    sh 'docker save ${IMAGE_NAME}:${APP_VERSION} | gzip > ${IMAGE_NAME}-v${APP_VERSION}.tar.gz'
                    archiveArtifacts artifacts: '*.tar.gz', fingerprint: true
                }
            }
        }
    }
    // DODANO BLOK SPRZĄTAJĄCY NA KONIEC
    post {
        always {
            cleanWs() 
        }
    }
}
