pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t express-km419774 .'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "TEST: placeholder"'
                // opcjonalnie:
                // sh 'docker run --rm express-km419774 npm test'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker stop express || true'
                sh 'docker rm express || true'
                sh 'docker run -d --name express -p 3000:3000 express-km419774'
            }
        }

        stage('Publish') {
            steps {
                sh 'docker tag express-km419774 localhost:5000/express-km419774'
                sh 'docker push localhost:5000/express-km419774'
            }
        }
    }
}
