apiVersion: v1
kind: Service
metadata:
  name: mdo-redis-rolling
  labels:
    app: mdo-redis
    deployment-strategy: rolling
spec:
  type: ClusterIP
  selector:
    app: mdo-redis
    deployment-strategy: rolling
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
