apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikacja-recreate
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web-recreate
  template:
    metadata:
      labels:
        app: web-recreate
    spec:
      containers:
      - name: nginx-kontener
        image: moja-aplikacja:v1
        ports:
        - containerPort: 80
