FROM ubuntu:latest

RUN apt-get update && apt-get install -y git build-essential tcl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/redis/redis.git

WORKDIR /app/redis
RUN make