apiVersion: apps/v1
kind: Deployment
metadata:
  name: strat-recreate
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apka-recreate
  template:
    metadata:
      labels:
        app: apka-recreate
    spec:
      containers:
      - name: apka
        image: kinsu-apka:v1
        imagePullPolicy: Never
