pipeline {
    agent any
    
    environment {
        APP_VERSION = "1.0.${BUILD_NUMBER}"
        IMAGE_NAME = "moj-kalkulator"
    }

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Clone & Setup') {
            steps {
                checkout scm
                sh "git clone https://github.com/actionsdemos/calculator.git temp-app"
            }
        }
        
        stage('Build') {
            steps {
                dir('FP422032/Sprawozdanie/files/Zaj6') {
                    sh "docker build --target builder -t ${IMAGE_NAME}-build:${BUILD_NUMBER} -f Dockerfile ../../../../temp-app/."
                }
            }
        }

        stage('Test') {
            steps {
                dir('FP422032/Sprawozdanie/files/Zaj6') {
                    sh "docker build --target tester -t ${IMAGE_NAME}-tester:${BUILD_NUMBER} -f Dockerfile ../../../../temp-app/."
                }
            }
        }
        
        stage('Deploy') {
            steps {
                dir('FP422032/Sprawozdanie/files/Zaj6') {
                    sh "docker build --target deploy -t ${IMAGE_NAME}:${APP_VERSION}-${GIT_COMMIT[0..6]} -f Dockerfile ../../../../temp-app/."
                }
            }
        }

        stage('Smoke Test') {
            steps {
                sh "docker run -d --name smoke-test-app -p 3000:3000 ${IMAGE_NAME}:${APP_VERSION}-${GIT_COMMIT[0..6]}"
                sleep 5
                
                sh 'docker run --rm --network container:smoke-test-app curlimages/curl -f http://localhost:3000 || (docker rm -f smoke-test-app && exit 1)'
                
                sh "docker rm -f smoke-test-app"
            }
        }
        
        stage('Publish') {
            steps {
                dir('FP422032/Sprawozdanie/files/Zaj6') {
                    archiveArtifacts artifacts: 'Dockerfile, Jenkinsfile', allowEmptyArchive: false
                }
            }
        }
    }
}