# docker-compose.yml
version: "3.9"

services:

  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: express-build:latest
    container_name: express_build_stage

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: express-test:latest
    container_name: express_test_stage
    depends_on:
      - build