apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f compose.yml convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: speedtest
  name: speedtest
spec:
  ports:
    - name: "8880"
      port: 8880
      targetPort: 8080
  selector:
    io.kompose.service: speedtest
