#!/bin/bash
commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")
pattern="^FT422048.*"

if [[ ! $commit_msg =~ $pattern ]]; then
  echo "ERROR: Commit message must start with 'FT422048'"
  exit 1
fi
