---
- name: Install docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Run nginx container
  docker_container:
    name: mynginx
    image: nginx
    state: started
    ports:
      - "8080:80"
