pipeline {
    agent any
    stages {
        stage('Clean') {
            steps {
                sh 'docker system prune -f || true'
            }
        }
        
        stage('Clone') {
            steps {
                git branch: 'KP419785', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2026_ITE.git'
            }
        }
        
        stage('Build') {
            steps {
                dir('ITE/grupa5/KP419785/Sprawozdanie6') {
                    sh 'docker build --no-cache -t portfinder-build -f Dockerfile.build .'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('ITE/grupa5/KP419785/Sprawozdanie6') {
                    sh 'docker build --no-cache --progress=plain -t portfinder-test -f Dockerfile.test . 2>&1 | tee test-output.log'
                    sh "mv test-output.log test-logs-${BUILD_NUMBER}.log"
                }
            }
            post {
                always {
                    dir('ITE/grupa5/KP419785/Sprawozdanie6') {
                        archiveArtifacts artifacts: "test-logs-${BUILD_NUMBER}.log", fingerprint: true
                    }
                }
            }
        }
        
        stage('Deploy (Smoke Test)') {
            steps {
                dir('ITE/grupa5/KP419785/Sprawozdanie6') {
                    sh 'docker build --no-cache -t portfinder-deploy -f Dockerfile.deploy .'
                    sh 'docker run --rm portfinder-deploy --help'
                }
            }
        }
        
        stage('Publish') {
            steps {
                dir('ITE/grupa5/KP419785/Sprawozdanie6') {
                    sh 'docker save portfinder-deploy | gzip > portfinder-image-${BUILD_NUMBER}.tar.gz'
                }
            }
            post {
                always {
                    dir('ITE/grupa5/KP419785/Sprawozdanie6') {
                        archiveArtifacts artifacts: '*.tar.gz', fingerprint: true
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Pipeline zakonczony ze statusem: ${currentBuild.currentResult}"
        }
    }
}
