apiVersion: apps/v1
kind: Deployment
metadata:
  name: jw422049-nginx-lab11
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jw422049-nginx-lab11
  template:
    metadata:
      labels:
        app: jw422049-nginx-lab11
    spec:
      containers:
        - name: jw422049-nginx
          image: jw422049-nginx-k8s:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
