apiVersion: v1
kind: Service
metadata:
  name: kacper-nginx-recreate-service
spec:
  selector:
    app: kacper-nginx-recreate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
