apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw423393-nginx-rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 25%
  selector:
    matchLabels:
      app: mw423393-nginx-rolling
  template:
    metadata:
      labels:
        app: mw423393-nginx-rolling
    spec:
      containers:
        - name: mw423393-nginx
          image: mw423393-nginx:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80