FROM ubuntu:24.04

RUN rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    apt-get update && \
    apt-get install -y --no-install-recommends build-essential make ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/makefile-for-c
COPY makefile-for-c/ .

RUN make