pipeline {
    agent any
    stages {
        stage('Collect') {
            steps {
                echo 'Pobieranie kodu z repozytorium'
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('KS423304/Spr6') {
                    echo 'Budowanie obrazu bazowego'
                    sh 'docker build -t aplikacja-build:latest -f Dockerfile.build .'
                }
            }
        }
        stage('Test') {
            steps {
                dir('KS423304/Spr6') {
                    echo 'Budowanie obrazu testowego i uruchamianie testów'
                    sh 'docker build -t aplikacja-test:latest -f Dockerfile.test .'
                    sh 'docker run --rm aplikacja-test:latest'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('KS423304/Spr6') {
                    echo 'Wdrażanie'
                    sh 'docker run --rm node:18-slim node -e "console.log(\'Deploy udany\')"'
                }
            }
        }
        stage('Publish') {
            steps {
                dir('KS423304/Spr6') {
                    echo 'Pakowanie i publikacja artefaktu'
                    sh '''
                    docker rm -f temp-pack || true
                    docker run --name temp-pack aplikacja-build:latest npm pack
                    docker cp temp-pack:/app/url-parse-1.5.10.tgz .
                    docker rm temp-pack
                    '''
                }
                archiveArtifacts artifacts: 'KS423304/Spr6/*.tgz', fingerprint: true
            }
        }
    }
}
