apiVersion: apps/v1
kind: Deployment
metadata:
  name: jw422049-nginx-rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 25%
  selector:
    matchLabels:
      app: jw422049-nginx-rolling
  template:
    metadata:
      labels:
        app: jw422049-nginx-rolling
    spec:
      containers:
        - name: jw422049-nginx
          image: jw422049-nginx-k8s:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
