pipeline {
    agent any
    stages {
        stage('Docker Build') {
            steps {
                dir('Sprawozdanie6/temp_code/api') {
                    sh 'ls -la'
                    sh 'docker build -t spring-api-prod -f docker/Dockerfile.prod .'
                }
            }
        }
        stage('Publish & Test') {
            steps {
                dir('Sprawozdanie6/temp_code/api') {
                    script {
                        sh "docker create --name temp-c-${env.BUILD_ID} spring-api-prod"
                        sh "docker cp temp-c-${env.BUILD_ID}:/usr/src/app/api.jar ./api-v${env.BUILD_ID}.jar"
                        sh "docker rm temp-c-${env.BUILD_ID}"
                    }
                    archiveArtifacts artifacts: "*.jar", fingerprint: true
                    
                    sh "docker run -d --name test-api-${env.BUILD_ID} spring-api-prod"
                    sh "sleep 10"
                    sh "docker logs test-api-${env.BUILD_ID} || true"
                    sh "docker stop test-api-${env.BUILD_ID} && docker rm test-api-${env.BUILD_ID}"
                }
            }
        }
    }
}