services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: libsodium-base

  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - builder