galaxy_info:
  author: PS422034
  description: Deploy Express.js app from tar.gz artifact
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies: []
