apiVersion: apps/v1
kind: Deployment
metadata:
  name: gn-nginx
  labels:
    app: gn-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gn-nginx
  template:
    metadata:
      labels:
        app: gn-nginx
    spec:
      containers:
      - name: gn-nginx
        image: gn-nginx:1.0
        ports:
        - containerPort: 80
