pipeline {
    agent any
    environment {
        APP_VERSION = "1.0.${env.BUILD_NUMBER}"
    }
    stages {
        stage('Cleanup') {
            steps {
                deleteDir()
            }
        }
        stage('Clone') {
            steps {
                dir('redis-code') {
                    git branch: 'unstable', url: 'https://github.com/redis/redis.git'
                }
                dir('my-config') {
                    git branch: 'FT422048', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2026_ITE.git'
                }
            }
        }
        stage('Build (CI)') {
            steps {
                sh 'cp my-config/ITE/grupa6/FT422048/Sprawozdanie3/Dockerfile.build redis-code/'
                dir('redis-code') {
                    sh "docker build -t redis-builder:${APP_VERSION} -f Dockerfile.build ."
                }
            }
        }
        stage('Test') {
            steps {
                sh 'cp my-config/ITE/grupa6/FT422048/Sprawozdanie3/Dockerfile.test redis-code/'
                dir('redis-code') {
                    sh "sed -i 's|^FROM.*|FROM redis-builder:${APP_VERSION}|' Dockerfile.test"
                    sh "docker build -t redis-tester:${APP_VERSION} -f Dockerfile.test ."
                    sh 'docker rm -f redis-test-run || true'
                    sh "docker run --name redis-test-run redis-tester:${APP_VERSION}"
                }
            }
        }
        stage('Deploy Image Creation') {
            steps {
                sh 'mkdir -p my-deploy-folder'
                sh 'cp my-config/ITE/grupa6/FT422048/Sprawozdanie6/Dockerfile.deploy my-deploy-folder/'
                dir('my-deploy-folder') {
                    sh "docker run --rm --entrypoint cat redis-builder:${APP_VERSION} /app/src/redis-server > redis-server"
                    sh "docker build -t redis-deploy:${APP_VERSION} -f Dockerfile.deploy ."
                }
            }
        }
        stage('Smoke Test') {
            steps {
                sh "docker run --rm redis-deploy:${APP_VERSION} --version"
            }
        }
        stage('Publish') {
            steps {
                dir('my-deploy-folder') {
                    sh "tar -czvf redis-${APP_VERSION}.tar.gz redis-server"
                    archiveArtifacts artifacts: "redis-${APP_VERSION}.tar.gz", fingerprint: true
                }
            }
        }
    }
}
