#pobranie i wejście do obrazu z sdk
FROM mcr.microsoft.com/dotnet/sdk:10.0

#ustawienie katalogu roboczego
WORKDIR /app

#klonowanie katalogu od jenkinsa
COPY . .

#build i kopia folcerow src i tests do output ale tylko gdy build sie powiodl
CMD ["bash", "-c", "dotnet build && cp -r src tests /output/"]
