[Orchestrators]
controller ansible_connection=local
[Orchestrators:vars]
ansible_python_interpreter=/usr/bin/python3

[Endpoints]
controlled ansible_host=recvr ansible_port=2020 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/ansible_key
[Endpoints:vars]
ansible_python_interpreter=/usr/bin/python3
