apiVersion: v1
kind: Service
metadata:
  name: mdo-redis-stable
  labels:
    app: mdo-redis
    deployment-strategy: canary
    track: stable
spec:
  type: ClusterIP
  selector:
    app: mdo-redis
    deployment-strategy: canary
    track: stable
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
