pipeline {
    agent any
    environment {
        IMAGE_NAME = "redis-custom:${env.BUILD_ID}"
        CONTAINER = "redis-deploy"
    }
    stages {
        stage('Checkout & Build') {
            steps {
                git branch: 
                
                sh "docker build -t ${IMAGE_NAME} ."
            }
        }

        stage('Deploy & Smoke Test') {
            steps {
                sh "docker rm -f ${CONTAINER} || true"
                sh "docker run -d --name ${CONTAINER} -p 6379:6379 ${IMAGE_NAME}"
                
                script {
                    sleep 5
                    sh "docker exec ${CONTAINER} redis-cli ping"
                }
            }
        }

        stage('Archive') {
            steps {
                
                sh "docker create --name extract ${IMAGE_NAME}"
                sh "docker export extract | gzip > redis-dist.tar.gz"
                sh "docker rm extract"
                archiveArtifacts 'redis-dist.tar.gz'
            }
        }
    }
    post {
        always {
            sh "docker logs ${CONTAINER} > redis.log 2>&1"
            archiveArtifacts '*.log'
            cleanWs()
        }
    }
}