apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-rolling
  labels:
    app: express-rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: express-rolling
  template:
    metadata:
      labels:
        app: express-rolling
        version: v1.0
    spec:
      containers:
      - name: express-app
        image: szymonmakow/express-app:v2.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-rolling-svc
spec:
  selector:
    app: express-rolling
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
