FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    tcl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone --depth 1 https://github.com/redis/redis.git .

RUN make
