services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: build-image
    container_name: build-container

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: test-image
    container_name: test-container
    depends_on:
      - build