---
- name: Podstawowe operacje administracyjne
  hosts: Endpoints
  become: yes
  tasks:
    - name: Wyslanie zadan ping
      ansible.builtin.ping:

    - name: Skopiowanie pliku inwentaryzacji na maszyne docelowa
      ansible.builtin.copy:
        src: inventory.ini
        dest: /tmp/inventory_backup.ini

    - name: Aktualizacja pakietow w systemie (apt update & upgrade)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      register: apt_status

    - name: Wyswietlenie statusu aktualizacji
      ansible.builtin.debug:
        var: apt_status.stdout_lines

    - name: Restart uslugi sshd
      ansible.builtin.systemd:
        name: ssh
        state: restarted

    - name: Restart uslugi rngd (ignoruj bledy jesli nie jest zainstalowana)
      ansible.builtin.systemd:
        name: rngd
        state: restarted
      ignore_errors: yes
