apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        track: production
    spec:
      containers:
      - name: nest-container
        image: nest-api:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 3000