FROM ubuntu:22.04

RUN apt-get update && apt-get install -y git


WORKDIR /src
RUN git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2026_ITE.git repo
WORKDIR /src/repo

CMD ["git", "branch"]