apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdo-deployment-rolling
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2   
      maxSurge: 25%       
  selector:
    matchLabels:
      app: mdo-rolling
  template:
    metadata:
      labels:
        app: mdo-rolling
    spec:
      containers:
      - name: web-container
        image: lemonx26/mdo-app:v1
        ports:
        - containerPort: 80
