---
- name: Sanity check - sprawdzenie polaczenia
  ansible.builtin.ping:

- name: Instalacja Dockera
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes

- name: Uruchomienie kontenera z aplikacji
  community.general.docker_container:
    name: moja_aplikacja_lab8
    image: nginx
    state: started
    ports:
      - "8080:80"
  become: yes
