#!/bin/bash

INITIALS="KP"
INDEX="419785"
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(head -n 1 "$COMMIT_MSG_FILE")
EXPECTED_PATTERN="^$INITIALS$INDEX"

if ! [[ "$COMMIT_MSG" =~ $EXPECTED_PATTERN ]]; then
    echo "BŁĄD: Wiadomość commita musi zaczynać się od ciągu: '$INITIALS$INDEX'"
    exit 1
fi
exit 0
