FROM debian:12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    tcl \
    libc6-dev \
    && rm -rf /var/lib/apt/lists/*

ENV REDIS_VER="8.6.2"

WORKDIR /build

RUN wget -q http://download.redis.io/releases/redis-${REDIS_VER}.tar.gz && \
    tar xzf redis-${REDIS_VER}.tar.gz && \
    mv redis-${REDIS_VER}/* . && \
    rm -rf redis-${REDIS_VER}.tar.gz