FROM ubuntu:latest
RUN apt update && apt install -y g++ make git && apt clean all
WORKDIR /src
RUN git clone https://github.com/Karro707/devops-cpp-app-test.git .
WORKDIR /src/devops-test/devops-test
RUN make build
