FROM python:3.10-slim
RUN apt-get update && apt-get install -y git make zip pandoc
WORKDIR /app
# Klonujemy projekt, który budowałeś w S4
RUN git clone https://github.com/yt-dlp/yt-dlp.git .
RUN make yt-dlp
CMD ["./yt-dlp", "--version"]