# Dockerfile.build
FROM node:20-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/axios/axios.git .

RUN npm install

RUN npm run build