- hosts: Endpoints
  become: yes
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

