
- hosts: Endpoints
  become: yes
  tasks:
    - name: Restart ssh
      service:
        name: ssh
        state: restarted

    - name: Restart rng-tools
      service:
        name: rng-tools
        state: restarted
