pipeline {
    agent any

    environment {
        BREANCH_NAME = 'MP420244'
        REPO_URL = 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2026_ITE.git'
        BUILD_DIR = 'build'
        ARTIFACT_BUILD = 'app-build.tar.gz'
        ARTIFACT_IMAGE = 'app-image.tar.gz'
        DOCKERFILE_BUILD_PATH = 'MP420244/Sprawozdanie7/Dockerfile.build'
        DOCKERFILE_TEST_PATH = 'MP420244/Sprawozdanie7/Dockerfile.test'
    }

    stages {
        stage('Clean up') {
            steps {
                echo 'STAGE: CLEAN UP'
                echo 'Cleaning up...'

                cleanWs()

                script {
                    sh "docker system prune -af || true"
                    sh "rm -rf ${BUILD_DIR} ${ARTIFACT_BUILD} || true"
                }
            }
        }
        stage('Clone') {
            steps {
                echo 'STAGE: CLONE'
                echo 'Cloning repository...'

                git branch: "${BREANCH_NAME}", url: "${REPO_URL}"
            }
        }
        stage('Build') {

            steps {
                echo 'STAGE: BUILD'
                echo 'Building application...'

                script {
                    sh "docker build --no-cache -t my-app-build -f ${DOCKERFILE_BUILD_PATH} ."
                    sh "docker run --rm my-app-build tar czf - /app/C-and-Cpp-Tests-with-CI-CD-Example > ${ARTIFACT_BUILD}"
                }
            }
        }
        stage('Test') {

            steps {
                echo 'STAGE: TEST'
                echo 'Testing application...'

                script {
                    sh "docker build --no-cache -t my-app-test -f ${DOCKERFILE_TEST_PATH} ."
                    
                    def status = sh(
                        script: "docker run --rm my-app-test > test-results.txt 2>&1",
                        returnStatus: true
                    )

                    if (status != 0) {
                        currentBuild.result = 'FAILURE'
                        error("Tests failed. See test-results.txt")
                    }
                }
            }
        }
        stage ('Package') {
            steps {
                echo 'STAGE: PACKAGE'
                echo 'Packaging docker image...'

                script {
                    sh "docker save my-app-build | gzip > ${ARTIFACT_IMAGE}"
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'STAGE: DEPLOY'
                echo 'Simulating deployment in fresh container...'

                script {
                    sh '''
                    docker load < ${ARTIFACT_IMAGE}
                    docker run --rm my-app-build make clean && make && ./test-library.out
                    '''
                }
            }
        }
        stage('Publish') {
            agent any
            
            steps {
                echo 'STAGE: PUBLISH'

                archiveArtifacts artifacts: "*.tag.gz, test-results.txt", fingerprint: true
            }
        }
    }
}