---
# tasks/main.yml
- name: Sanity Check - Wolne miejsce
  ansible.builtin.shell: "df -h / | tail -1 | awk '{print $4}'"
  register: disk_free

- name: Sprawdź czy system to Debian/Ubuntu
  ansible.builtin.assert:
    that:
      - ansible_os_family == "Debian"
    fail_msg: "Rola wspiera tylko systemy z rodziny Debian!"

- name: Instalacja Dockera i zależności
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker
    state: present
    update_cache: yes

- name: Upewnij się, że Docker działa
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Pobierz obraz i uruchom kontener
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ host_port }}:{{ container_port }}"

- name: Czekaj na uruchomienie aplikacji
  ansible.builtin.pause:
    seconds: 5

- name: Zweryfikuj łączność z kontenerem
  ansible.builtin.uri:
    url: "http://localhost:{{ host_port }}"
    status_code: 200
  register: result
  ignore_errors: yes

- name: Zatrzymaj i usuń kontener
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: absent