pipeline {
    agent any

    environment {
        REGISTRY = 'mrntex'
        BUILDER_IMAGE = "cpython-builder:${BUILD_NUMBER}"
        TESTER_IMAGE = "cpython-tester:${BUILD_NUMBER}"
        DEPLOY_IMAGE = "cpython-deploy:3.13-build${BUILD_NUMBER}"
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Cleanup Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Build Builder Image') {
            steps {
                script {
                    sh "docker build --pull -f Dockerfile.build -t ${BUILDER_IMAGE} -t cpython-builder:latest ."
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    sh "docker build -f Dockerfile.test -t ${TESTER_IMAGE} ."
                    sh "docker rm -f cpython-test-run || true"
                    sh "docker run --name cpython-test-run ${TESTER_IMAGE}"
                    sh "docker logs cpython-test-run > test-results.log"
                }
            }
            post {
                always {
                    archiveArtifacts artifacts: 'test-results.log', fingerprint: true
                    sh "docker rm -f cpython-test-run || true"
                }
            }
        }

        stage('Build Deploy Image') {
            steps {
                script {
                    sh "docker build -f Dockerfile.deploy -t ${DEPLOY_IMAGE} ."
                }
            }
        }

        stage('Smoke Test / Local Deploy') {
            steps {
                script {
                    sh "docker run --rm ${DEPLOY_IMAGE} python3 -c \"print('Smoke test przeszedł pomyślnie!')\""
                }
            }
        }

        stage('Publish Image to Registry') {
            steps {
                script {
                    sh "docker tag ${DEPLOY_IMAGE} ${REGISTRY}/${DEPLOY_IMAGE}"
                    
                    echo "Obraz został przygotowany jako: ${DEPLOY_IMAGE}"
                }
            }
        }
    }

    post {
        always {
            script {
                sh "docker rmi ${BUILDER_IMAGE} ${TESTER_IMAGE} ${DEPLOY_IMAGE} || true"
            }
            cleanWs()
        }
        success {
            echo "Pipeline zakonczony sukcesem! Artefakt gotowy do pobrania z rejestru."
        }
    }
}