apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab11-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 1
  selector:
    matchLabels:
      app: lab11-app
  template:
    metadata:
      labels:
        app: lab11-app
    spec:
      containers:
      - name: web
        image: moja-apka:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
